name: Deploy to cPanel via SFTP

on:
  push:
    branches:
      - main   # Replace with the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      # Step 2: Install lftp client
#      - name: Install lftp client
#        run: sudo apt-get install -y lftp
#
#      # Step 3: Set up SFTP with the necessary credentials
#      - name: Deploy files to cPanel via SFTP
#        run: |
#          lftp -u ${{ secrets.CPANEL_USER }},${{ secrets.CPANEL_PASS }} sftp://${{ secrets.CPANEL_HOST }} -e "set ssl:verify-certificate false; mirror -R ./ /home/code/public_html/codefly/ && quit"
#        env:
#          CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
#          CPANEL_USER: ${{ secrets.CPANEL_USER }}
#          CPANEL_PASS: ${{ secrets.CPANEL_PASS }}
